sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t "$DOCKER_USERNAME"/cecs550-software-engineering:$TRAVIS_BUILD_NUMBER source

after_success:
  - docker push "$DOCKER_USERNAME"/cecs550-software-engineering:$TRAVIS_BUILD_NUMBER

