sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t "$DOCKER_USERNAME"/cecs550-software-engineering:v$TRAVIS_BUILD_NUMBER -t "$DOCKER_USERNAME"/cecs550-software-engineering:latest source

after_success:
  - docker push "$DOCKER_USERNAME"/cecs550-software-engineering:v$TRAVIS_BUILD_NUMBER

deploy:
  - provider: script
    script:
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      az login --service-principal -u "$AZURE_SERVICE_PRINCIPAL_CLIENT_ID" -p "$AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
      az account set -s "Azure for Students"
      az webapp config container set --docker-custom-image-name gfrankel/cecs550-software-engineering:v$TRAVIS_BUILD_NUMBER --resource-group rgPantryToTable --name pantry-to-table
      until $(curl --output /dev/null --silent --head --fail http://pantry-to-table.azurewebsites.net); do printf '.'; sleep 5; done



