sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t "$DOCKER_USERNAME"/cecs550-software-engineering:v$TRAVIS_BUILD_NUMBER -t "$DOCKER_USERNAME"/cecs550-software-engineering:latest source

after_success:
  - docker push "$DOCKER_USERNAME"/cecs550-software-engineering:v$TRAVIS_BUILD_NUMBER

deploy:
  provider: azure_web_apps
  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
  slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
