sudo: required

language: python

services:
  - docker


before_script:
  - echo Docker Tag: $TRAVIS_JOB_ID


# script:
#   - echo Docker Tag: $TRAVIS_JOB_ID
#   - cd source
#   - docker build -t gfrankel/cecs550-software-engineering:$TRAVIS_JOB_ID .
#   - docker push gfrankel/cecs550-software-engineering:$TRAVIS_JOB_ID
#   provider: script
