
dist: trusty

sudo: required

services:
  - docker

script:
  - echo Docker Tag: $TRAVIS_JOB_ID
  - docker build -t gfrankel/cecs550-software-engineering:$TRAVIS_JOB_ID .
  - docker push gfrankel/cecs550-software-engineering:$TRAVIS_JOB_ID